#!/bin/bash
# Fetch species photos from Wikimedia Commons
WILDLIFE_DIR="/Users/thomascrisp/VLT App/Wildlife"

fetch_image() {
    local folder_name="$1"
    local scientific_name="$2"
    local photo_name="$3"
    local dir="$WILDLIFE_DIR/$folder_name"
    local filepath="$dir/$photo_name"

    if [ -f "$filepath" ]; then
        echo "SKIP: $folder_name (exists)"
        return 0
    fi

    mkdir -p "$dir"

    local search_term=$(echo "$scientific_name" | sed 's/ /%20/g')
    local api_url="https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${search_term}&gsrnamespace=6&gsrlimit=5&prop=imageinfo&iiprop=url|mime&iiurlwidth=1200&format=json"

    local response=$(curl -s -A "VLT-TrailGuide/1.0" "$api_url")

    # Extract first jpeg thumburl using grep/sed
    local img_url=$(echo "$response" | grep -o '"thumburl":"[^"]*"' | head -1 | sed 's/"thumburl":"//;s/"//')

    if [ -z "$img_url" ]; then
        # Fallback: try with common name
        local common_part=$(echo "$folder_name" | sed 's/,.*//')
        local alt_search=$(echo "${common_part}" | sed 's/ /%20/g')
        api_url="https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${alt_search}%20plant&gsrnamespace=6&gsrlimit=5&prop=imageinfo&iiprop=url|mime&iiurlwidth=1200&format=json"
        response=$(curl -s -A "VLT-TrailGuide/1.0" "$api_url")
        img_url=$(echo "$response" | grep -o '"thumburl":"[^"]*"' | head -1 | sed 's/"thumburl":"//;s/"//')
    fi

    if [ -n "$img_url" ]; then
        curl -s -L -o "$filepath" "$img_url"
        if [ -f "$filepath" ] && [ -s "$filepath" ]; then
            local size=$(wc -c < "$filepath" | tr -d ' ')
            echo "OK: $folder_name (${size} bytes)"
        else
            echo "FAIL: $folder_name (download failed)"
            rm -f "$filepath"
        fi
    else
        echo "FAIL: $folder_name (no image found)"
    fi
    # Rate limit
    sleep 0.5
}

echo "Fetching species images from Wikimedia Commons..."
echo "================================================="

fetch_image "Beech, American" "Fagus grandifolia" "Beech, American.jpg"
fetch_image "Beggar-ticks, Devil's" "Bidens frondosa" "Beggar-ticks, Devil's.jpg"
fetch_image "Bellflower, Creeping" "Campanula rapunculoides" "Bellflower, Creeping.jpg"
fetch_image "Bellflower, Marsh" "Campanula aparinoides" "Bellflower, Marsh.jpg"
fetch_image "Bellflower, Scotch" "Campanula rotundifolia" "Bellflower, Scotch.jpg"
fetch_image "Bentgrass, Autumn" "Agrostis perennans" "Bentgrass, Autumn.jpg"
fetch_image "Bentgrass, Creeping" "Agrostis stolonifera" "Bentgrass, Creeping.jpg"
fetch_image "Bentgrass, Redtop" "Agrostis gigantea" "Bentgrass, Redtop.jpg"
fetch_image "Bentgrass, Rhode Island" "Agrostis capillaris" "Bentgrass, Rhode Island.jpg"
fetch_image "Bentgrass, Rough" "Agrostis scabra" "Bentgrass, Rough.jpg"
fetch_image "Bindweed, Black" "Fallopia convolvulus" "Bindweed, Black.jpg"
fetch_image "Bindweed, Crested" "Fallopia cristata" "Bindweed, Crested.jpg"
fetch_image "Bindweed, Fringed" "Fallopia cilinodis" "Bindweed, Fringed.jpg"
fetch_image "Bindweed, Hedge False" "Calystegia sepium" "Bindweed, Hedge False.jpg"
fetch_image "Birch, Blue" "Betula caerulea" "Birch, Blue.jpg"
fetch_image "Birch, Gray" "Betula populifolia" "Birch, Gray.jpg"
fetch_image "Birch, Heart-leaved Paper" "Betula cordifolia" "Birch, Heart-leaved Paper.jpg"
fetch_image "Birch, Paper" "Betula papyrifera" "Birch, Paper.jpg"
fetch_image "Birch, Yellow" "Betula alleghaniensis" "Birch, Yellow.jpg"
fetch_image "Bitter-cress, Small-flowered" "Cardamine parviflora" "Bitter-cress, Small-flowered.jpg"
fetch_image "Bittersweet, Asian" "Celastrus orbiculatus" "Bittersweet, Asian.jpg"
fetch_image "Blackberry, Arching" "Rubus recurvicaulis" "Blackberry, Arching.jpg"
fetch_image "Blackberry, Bristly" "Rubus hispidus" "Blackberry, Bristly.jpg"
fetch_image "Blackberry, Common" "Rubus allegheniensis" "Blackberry, Common.jpg"
fetch_image "Blackberry, Northern" "Rubus flagellaris" "Blackberry, Northern.jpg"
fetch_image "Blackberry, Showy" "Rubus elegantulus" "Blackberry, Showy.jpg"
fetch_image "Blackberry, Smooth" "Rubus canadensis" "Blackberry, Smooth.jpg"
fetch_image "Blackberry, Vermont" "Rubus vermontanus" "Blackberry, Vermont.jpg"
fetch_image "Bladderwort, Greater" "Utricularia vulgaris" "Bladderwort, Greater.jpg"
fetch_image "Bladderwort, Mixed" "Utricularia geminiscapa" "Bladderwort, Mixed.jpg"
fetch_image "Aster, Blake's" "Oclemena blakei" "Aster, Blake's.jpg"
fetch_image "Blue Grass, Flat-stemmed" "Poa compressa" "Blue Grass, Flat-stemmed.jpg"
fetch_image "Blue Grass, Fowl" "Poa palustris" "Blue Grass, Fowl.jpg"
fetch_image "Blue Grass, Wood" "Poa nemoralis" "Blue Grass, Wood.jpg"
fetch_image "Blue-eyed-grass, Narrow-leaved" "Sisyrinchium angustifolium" "Blue-eyed-grass, Narrow-leaved.jpg"
fetch_image "Blue-eyed-grass, Strict" "Sisyrinchium montanum" "Blue-eyed-grass, Strict.jpg"
fetch_image "Firmoss, Shining" "Huperzia lucidula" "Firmoss, Shining.jpg"
fetch_image "Flax, White" "Linum catharticum" "Flax, White.jpg"
fetch_image "Fleabane, Canada" "Erigeron canadensis" "Fleabane, Canada.jpg"
fetch_image "Fleabane, Rough" "Erigeron strigosus" "Fleabane, Rough.jpg"
fetch_image "Floating-heart" "Nymphoides cordata" "Floating-heart.jpg"
fetch_image "Foam-flower" "Tiarella cordifolia" "Foam-flower.jpg"
fetch_image "Forget-me-not, Field" "Myosotis arvensis" "Forget-me-not, Field.jpg"
fetch_image "Foxtail, Chinese" "Setaria faberi" "Foxtail, Chinese.jpg"
fetch_image "Foxtail, Yellow" "Setaria pumila" "Foxtail, Yellow.jpg"
fetch_image "Garlic-mustard" "Alliaria petiolata" "Garlic-mustard.jpg"
fetch_image "Germander, American" "Teucrium canadense" "Germander, American.jpg"
fetch_image "Glasswort, Common" "Salicornia depressa" "Glasswort, Common.jpg"
fetch_image "Goat's Beard, Meadow" "Tragopogon pratensis" "Goat's Beard, Meadow.jpg"
fetch_image "Goldenrod, Bog" "Solidago uliginosa" "Goldenrod, Bog.jpg"
fetch_image "Goldenrod, Canada" "Solidago canadensis" "Goldenrod, Canada.jpg"
fetch_image "Goldenrod, Common Grass-leaved" "Euthamia graminifolia" "Goldenrod, Common Grass-leaved.jpg"
fetch_image "Goldenrod, Downy" "Solidago puberula" "Goldenrod, Downy.jpg"
fetch_image "Goldenrod, Early" "Solidago juncea" "Goldenrod, Early.jpg"
fetch_image "Goldenrod, Gray" "Solidago nemoralis" "Goldenrod, Gray.jpg"
fetch_image "Goldenrod, Seaside" "Solidago sempervirens" "Goldenrod, Seaside.jpg"
fetch_image "Goldenrod, Smooth" "Solidago gigantea" "Goldenrod, Smooth.jpg"
fetch_image "Goldenrod, Tall" "Solidago altissima" "Goldenrod, Tall.jpg"
fetch_image "Goldenrod, White" "Solidago bicolor" "Goldenrod, White.jpg"
fetch_image "Goldenrod, Wrinkle-leaved" "Solidago rugosa" "Goldenrod, Wrinkle-leaved.jpg"
fetch_image "Goldthread, Three-leaved" "Coptis trifolia" "Goldthread, Three-leaved.jpg"
fetch_image "Gooseberry, Hairy-stemmed" "Ribes hirtellum" "Gooseberry, Hairy-stemmed.jpg"
fetch_image "Goosefoot, Desert" "Chenopodium pratericola" "Goosefoot, Desert.jpg"
fetch_image "Goosefoot, White" "Chenopodium album" "Goosefoot, White.jpg"
fetch_image "Grass, Orchard" "Dactylis glomerata" "Grass, Orchard.jpg"
fetch_image "Grass, Tall Oat" "Arrhenatherum elatius" "Grass, Tall Oat.jpg"
fetch_image "Grass, Vanilla Sweet" "Anthoxanthum nitens" "Grass, Vanilla Sweet.jpg"
fetch_image "Greenwood, Dyer's" "Genista tinctoria" "Greenwood, Dyer's.jpg"
fetch_image "Ground-cedar, Northern" "Diphasiastrum complanatum" "Ground-cedar, Northern.jpg"
fetch_image "Groundsel, New England" "Packera schweinitziana" "Groundsel, New England.jpg"
fetch_image "Grove-sandwort, Blunt-leaved" "Moehringia lateriflora" "Grove-sandwort, Blunt-leaved.jpg"
fetch_image "Hair Grass, Common" "Deschampsia flexuosa" "Hair Grass, Common.jpg"
fetch_image "Hair Grass, Tufted" "Deschampsia cespitosa" "Hair Grass, Tufted.jpg"
fetch_image "Hair Sedge, Tufted" "Bulbostylis capillaris" "Hair Sedge, Tufted.jpg"
fetch_image "Hawkweed, Canada" "Hieracium kalmii" "Hawkweed, Canada.jpg"
fetch_image "Hawkweed, Mouse-ear" "Hieracium pilosella" "Hawkweed, Mouse-ear.jpg"
fetch_image "Hawkweed, Orange" "Hieracium aurantiacum" "Hawkweed, Orange.jpg"
fetch_image "Hawkweed, Panicled" "Hieracium paniculatum" "Hawkweed, Panicled.jpg"
fetch_image "Hawkweed, Rough" "Hieracium scabrum" "Hawkweed, Rough.jpg"
fetch_image "Hawkweed, Yellow" "Hieracium caespitosum" "Hawkweed, Yellow.jpg"
fetch_image "Hawthorn, Miss Jones'" "Crataegus jonesiae" "Hawthorn, Miss Jones'.jpg"
fetch_image "Hazelnut, Beaked" "Corylus cornuta" "Hazelnut, Beaked.jpg"
fetch_image "Helleborine, Broad-leaved" "Epipactis helleborine" "Helleborine, Broad-leaved.jpg"
fetch_image "Hemlock, Eastern" "Tsuga canadensis" "Hemlock, Eastern.jpg"
fetch_image "Hemp-nettle, Brittle-stemmed" "Galeopsis tetrahit" "Hemp-nettle, Brittle-stemmed.jpg"
fetch_image "Hemp-nettle, Split-lipped" "Galeopsis bifida" "Hemp-nettle, Split-lipped.jpg"
fetch_image "Highbush-cranberry" "Viburnum opulus" "Highbush-cranberry.jpg"
fetch_image "Holly, Mountain" "Ilex mucronata" "Holly, Mountain.jpg"
fetch_image "Honeysuckle, American" "Lonicera canadensis" "Honeysuckle, American.jpg"
fetch_image "Honeysuckle, Bush" "Diervilla lonicera" "Honeysuckle, Bush.jpg"
fetch_image "Honeysuckle, Morrow's" "Lonicera morrowii" "Honeysuckle, Morrow's.jpg"
fetch_image "Horsetail, Field" "Equisetum arvense" "Horsetail, Field.jpg"
fetch_image "Horsetail, Wood" "Equisetum sylvaticum" "Horsetail, Wood.jpg"
fetch_image "Huckleberry, Black" "Gaylussacia baccata" "Huckleberry, Black.jpg"
fetch_image "Indian-pipe, One-flowered" "Monotropa uniflora" "Indian-pipe, One-flowered.jpg"
fetch_image "Iris, Blue" "Iris versicolor" "Iris, Blue.jpg"
fetch_image "Jack-in-the-pulpit" "Arisaema triphyllum" "Jack-in-the-pulpit.jpg"
fetch_image "Juniper, Common" "Juniperus communis" "Juniper, Common.jpg"
fetch_image "Juniper, Creeping" "Juniperus horizontalis" "Juniper, Creeping.jpg"
fetch_image "Knapweed, Black" "Centaurea nigra" "Knapweed, Black.jpg"
fetch_image "Knapweed, Brown" "Centaurea jacea" "Knapweed, Brown.jpg"
fetch_image "Knotweed, Dooryard" "Polygonum aviculare" "Knotweed, Dooryard.jpg"
fetch_image "Knotweed, Fowler's" "Polygonum fowleri" "Knotweed, Fowler's.jpg"
fetch_image "Knotweed, Japanese" "Fallopia japonica" "Knotweed, Japanese.jpg"
fetch_image "Knotweed, Prairie" "Polygonum buxiforme" "Knotweed, Prairie.jpg"
fetch_image "Labrador-tea" "Rhododendron groenlandicum" "Labrador-tea.jpg"
fetch_image "Ladies'-tresses, Hooded" "Spiranthes romanzoffiana" "Ladies'-tresses, Hooded.jpg"
fetch_image "Ladies'-tresses, Nodding" "Spiranthes cernua" "Ladies'-tresses, Nodding.jpg"
fetch_image "Lady's Slipper, Pink" "Cypripedium acaule" "Lady's Slipper, Pink.jpg"
fetch_image "Larch, American" "Larix laricina" "Larch, American.jpg"
fetch_image "Larkspur, Tall" "Delphinium exaltatum" "Larkspur, Tall.jpg"
fetch_image "Leatherleaf" "Chamaedaphne calyculata" "Leatherleaf.jpg"
fetch_image "Lobelia, Bladder-pod" "Lobelia inflata" "Lobelia, Bladder-pod.jpg"
fetch_image "Locust, Black" "Robinia pseudoacacia" "Locust, Black.jpg"
fetch_image "Loosestrife, Garden Yellow" "Lysimachia vulgaris" "Loosestrife, Garden Yellow.jpg"
fetch_image "Loosestrife, Purple" "Lythrum salicaria" "Loosestrife, Purple.jpg"
fetch_image "Loosestrife, Swamp Yellow" "Lysimachia terrestris" "Loosestrife, Swamp Yellow.jpg"
fetch_image "Loosestrife, Whorled Yellow" "Lysimachia quadrifolia" "Loosestrife, Whorled Yellow.jpg"
fetch_image "Lupine, Blue" "Lupinus polyphyllus" "Lupine, Blue.jpg"
fetch_image "Lyme Grass, American" "Leymus mollis" "Lyme Grass, American.jpg"
fetch_image "Mallow, Musk" "Malva moschata" "Mallow, Musk.jpg"
fetch_image "Manna Grass, American" "Glyceria grandis" "Manna Grass, American.jpg"
fetch_image "Manna Grass, Fowl" "Glyceria striata" "Manna Grass, Fowl.jpg"
fetch_image "Manna Grass, Rattlesnake" "Glyceria canadensis" "Manna Grass, Rattlesnake.jpg"
fetch_image "Maple, Mountain" "Acer spicatum" "Maple, Mountain.jpg"
fetch_image "Maple, Norway" "Acer platanoides" "Maple, Norway.jpg"
fetch_image "Maple, Red" "Acer rubrum" "Maple, Red.jpg"
fetch_image "Maple, Striped" "Acer pensylvanicum" "Maple, Striped.jpg"
fetch_image "Maple, Sugar" "Acer saccharum" "Maple, Sugar.jpg"
fetch_image "Marigold, Pot" "Calendula officinalis" "Marigold, Pot.jpg"
fetch_image "Marjoram, Wild" "Origanum vulgare" "Marjoram, Wild.jpg"
fetch_image "Marsh-pennywort" "Hydrocotyle americana" "Marsh-pennywort.jpg"
fetch_image "Mayflower, Canada" "Maianthemum canadense" "Mayflower, Canada.jpg"
fetch_image "Meadow-foxtail, Field" "Alopecurus pratensis" "Meadow-foxtail, Field.jpg"
fetch_image "Meadow-foxtail, Marsh" "Alopecurus geniculatus" "Meadow-foxtail, Marsh.jpg"
fetch_image "Meadow-rue, Tall" "Thalictrum pubescens" "Meadow-rue, Tall.jpg"
fetch_image "Meadowsweet, Rosy" "Spiraea tomentosa" "Meadowsweet, Rosy.jpg"
fetch_image "Meadowsweet, White" "Spiraea alba" "Meadowsweet, White.jpg"
fetch_image "Medick, Black" "Medicago lupulina" "Medick, Black.jpg"
fetch_image "Milkweed, Common" "Asclepias syriaca" "Milkweed, Common.jpg"
fetch_image "Mint, Field" "Mentha arvensis" "Mint, Field.jpg"
fetch_image "Mint, Ginger Spear" "Mentha X gracilis" "Mint, Ginger Spear.jpg"
fetch_image "Mistletoe, Dwarf" "Arceuthobium pusillum" "Mistletoe, Dwarf.jpg"
fetch_image "Mountain-ash, American" "Sorbus americana" "Mountain-ash, American.jpg"
fetch_image "Mountain-ash, European" "Sorbus aucuparia" "Mountain-ash, European.jpg"
fetch_image "Mountain-ash, Showy" "Sorbus decora" "Mountain-ash, Showy.jpg"
fetch_image "Mullein, Common" "Verbascum thapsus" "Mullein, Common.jpg"
fetch_image "Mustard, Chinese" "Brassica juncea" "Mustard, Chinese.jpg"
fetch_image "Nettle, Small-spiked False" "Boehmeria cylindrica" "Nettle, Small-spiked False.jpg"
fetch_image "Nettle, Stinging" "Urtica dioica" "Nettle, Stinging.jpg"
fetch_image "Nightshade, Climbing" "Solanum dulcamara" "Nightshade, Climbing.jpg"
fetch_image "Nightshade, European Black" "Solanum nigrum" "Nightshade, European Black.jpg"
fetch_image "Oak, Northern Red" "Quercus rubra" "Oak, Northern Red.jpg"
fetch_image "Oatgrass, Flattened" "Danthonia compressa" "Oatgrass, Flattened.jpg"
fetch_image "Oatgrass, Poverty" "Danthonia spicata" "Oatgrass, Poverty.jpg"
fetch_image "Orache, Bracted" "Atriplex glabriuscula" "Orache, Bracted.jpg"
fetch_image "Orache, Hastate-leaved" "Atriplex prostrata" "Orache, Hastate-leaved.jpg"
fetch_image "Orache, Maritime" "Atriplex acadiensis" "Orache, Maritime.jpg"
fetch_image "Orchid, Loesel's Wide-lipped" "Liparis loeselii" "Orchid, Loesel's Wide-lipped.jpg"
fetch_image "Orpine, Purple" "Hylotelephium telephium" "Orpine, Purple.jpg"
fetch_image "Oxtongue, Hawkweed" "Picris hieracioides" "Oxtongue, Hawkweed.jpg"
fetch_image "Panicgrass, Hairy Rosette-" "Dichanthelium acuminatum" "Panicgrass, Hairy Rosette-.jpg"
fetch_image "Panicgrass, Northern Rosette-" "Dichanthelium boreale" "Panicgrass, Northern Rosette-.jpg"
fetch_image "Pearlwort, Birds-eye" "Sagina procumbens" "Pearlwort, Birds-eye.jpg"
fetch_image "Pearlwort, Knotted" "Sagina nodosa" "Pearlwort, Knotted.jpg"
fetch_image "Pickerelweed" "Pontederia cordata" "Pickerelweed.jpg"
fetch_image "Pimpernel, Scarlet" "Lysimachia arvensis" "Pimpernel, Scarlet.jpg"
fetch_image "Pine-sap, Yellow" "Hypopitys monotropa" "Pine-sap, Yellow.jpg"
fetch_image "Pine, Pitch" "Pinus rigida" "Pine, Pitch.jpg"
fetch_image "Pine, Red" "Pinus resinosa" "Pine, Red.jpg"
fetch_image "Pine, White" "Pinus strobus" "Pine, White.jpg"
fetch_image "Pink, Deptford" "Dianthus armeria" "Pink, Deptford.jpg"
fetch_image "Pink, Maiden" "Dianthus deltoides" "Pink, Maiden.jpg"
fetch_image "Pinweed, Round-fruited" "Lechea intermedia" "Pinweed, Round-fruited.jpg"
fetch_image "Pitcherplant, Purple" "Sarracenia purpurea" "Pitcherplant, Purple.jpg"
fetch_image "Plantain, Common" "Plantago major" "Plantain, Common.jpg"
fetch_image "Plantain, English" "Plantago lanceolata" "Plantain, English.jpg"
fetch_image "Plantain, Seaside" "Plantago maritima" "Plantain, Seaside.jpg"
fetch_image "Plum, Canada" "Prunus nigra" "Plum, Canada.jpg"
fetch_image "Pogonia, Rose" "Pogonia ophioglossoides" "Pogonia, Rose.jpg"
fetch_image "Poison-ivy" "Toxicodendron radicans" "Poison-ivy.jpg"
fetch_image "Poison-ivy, Western" "Toxicodendron rydbergii" "Poison-ivy, Western.jpg"
fetch_image "Polypody, Appalachian" "Polypodium appalachianum" "Polypody, Appalachian.jpg"
fetch_image "Polypody, Rock" "Polypodium virginianum" "Polypody, Rock.jpg"
fetch_image "Pond-lily, Bullhead" "Nuphar variegata" "Pond-lily, Bullhead.jpg"
fetch_image "Pondweed, Alga-like" "Potamogeton confervoides" "Pondweed, Alga-like.jpg"
fetch_image "Pondweed, Oakes'" "Potamogeton oakesianus" "Pondweed, Oakes'.jpg"
fetch_image "Pondweed, Ribbon-leaved" "Potamogeton epihydrus" "Pondweed, Ribbon-leaved.jpg"
fetch_image "Poplar, Balsam" "Populus balsamifera" "Poplar, Balsam.jpg"
fetch_image "Princes-pine, Spotted" "Chimaphila umbellata" "Princes-pine, Spotted.jpg"
fetch_image "Pumpkin" "Cucurbita pepo" "Pumpkin.jpg"
fetch_image "Pussytoes, Small" "Antennaria howellii" "Pussytoes, Small.jpg"
fetch_image "Queen Anne's Lace" "Daucus carota" "Queen Anne's Lace.jpg"
fetch_image "Quickweed" "Galinsoga quadriradiata" "Quickweed.jpg"
fetch_image "Radish, Wild" "Raphanus raphanistrum" "Radish, Wild.jpg"
fetch_image "Ragweed, Common" "Ambrosia artemisiifolia" "Ragweed, Common.jpg"
fetch_image "Ragwort, Common" "Senecio vulgaris" "Ragwort, Common.jpg"
fetch_image "Ragwort, Tansy" "Jacobaea vulgaris" "Ragwort, Tansy.jpg"
fetch_image "Ragwort, Woodland" "Senecio sylvaticus" "Ragwort, Woodland.jpg"
fetch_image "Raspberry, Dwarf" "Rubus pubescens" "Raspberry, Dwarf.jpg"
fetch_image "Raspberry, Red" "Rubus idaeus" "Raspberry, Red.jpg"
fetch_image "Rattlesnake-root, Three-leaved" "Nabalus trifoliatus" "Rattlesnake-root, Three-leaved.jpg"
fetch_image "Rattlesnake-plantain, Dwarf" "Goodyera repens" "Rattlesnake-plantain, Dwarf.jpg"
fetch_image "Reed Grass, Canada" "Calamagrostis canadensis" "Reed Grass, Canada.jpg"
fetch_image "Rhodora" "Rhododendron canadense" "Rhodora.jpg"
fetch_image "Rose, Beach" "Rosa rugosa" "Rose, Beach.jpg"
fetch_image "Rose, Cinnamon" "Rosa cinnamomea" "Rose, Cinnamon.jpg"
fetch_image "Rose, Rambler" "Rosa multiflora" "Rose, Rambler.jpg"
fetch_image "Rose, Shining" "Rosa nitida" "Rose, Shining.jpg"
fetch_image "Rose, Swamp" "Rosa palustris" "Rose, Swamp.jpg"
fetch_image "Rose, Sweet-briar" "Rosa rubiginosa" "Rose, Sweet-briar.jpg"
fetch_image "Rose, Virginia" "Rosa virginiana" "Rose, Virginia.jpg"
fetch_image "Rush, Baltic" "Juncus balticus" "Rush, Baltic.jpg"
fetch_image "Rush, Brown-fruited" "Juncus pelocarpus" "Rush, Brown-fruited.jpg"
fetch_image "Rush, Canada" "Juncus canadensis" "Rush, Canada.jpg"
fetch_image "Rush, Common Soft" "Juncus effusus" "Rush, Common Soft.jpg"
fetch_image "Rush, Dudley's" "Juncus dudleyi" "Rush, Dudley's.jpg"
fetch_image "Rush, Path" "Juncus tenuis" "Rush, Path.jpg"
fetch_image "Rush, Pylae's Soft" "Juncus pylaei" "Rush, Pylae's Soft.jpg"
fetch_image "Rush, Saltmarsh" "Juncus gerardii" "Rush, Saltmarsh.jpg"
fetch_image "Rush, Short-tailed" "Juncus brevicaudatus" "Rush, Short-tailed.jpg"
fetch_image "Rush, Thread" "Juncus filiformis" "Rush, Thread.jpg"
fetch_image "Rush, Toad" "Juncus bufonius" "Rush, Toad.jpg"
fetch_image "Russian-olive" "Elaeagnus angustifolia" "Russian-olive.jpg"
fetch_image "Saltgrass" "Distichlis spicata" "Saltgrass.jpg"
fetch_image "Sand-spurry, Canada" "Spergularia canadensis" "Sand-spurry, Canada.jpg"
fetch_image "Sand-spurry, Red" "Spergularia rubra" "Sand-spurry, Red.jpg"
fetch_image "Sand-spurry, Saltmarsh" "Spergularia marina" "Sand-spurry, Saltmarsh.jpg"
fetch_image "Sandwort, Seaside" "Honckenya peploides" "Sandwort, Seaside.jpg"
fetch_image "Sandwort, Thyme-leaved" "Arenaria serpyllifolia" "Sandwort, Thyme-leaved.jpg"
fetch_image "Sarsaparilla, Bristly" "Aralia hispida" "Sarsaparilla, Bristly.jpg"
fetch_image "Sarsaparilla, Wild" "Aralia nudicaulis" "Sarsaparilla, Wild.jpg"
fetch_image "Sea-blite, American" "Suaeda calceoliformis" "Sea-blite, American.jpg"
fetch_image "Sea-blite, Herbaceous" "Suaeda maritima" "Sea-blite, Herbaceous.jpg"
fetch_image "Sea-lavender, Carolina" "Limonium carolinianum" "Sea-lavender, Carolina.jpg"
fetch_image "Sea-milkwort" "Lysimachia maritima" "Sea-milkwort.jpg"
fetch_image "Sea-rocket, American" "Cakile edentula" "Sea-rocket, American.jpg"
fetch_image "Sedge, Awl-fruited" "Carex stipata" "Sedge, Awl-fruited.jpg"
fetch_image "Sedge, Billings'" "Carex billingsii" "Sedge, Billings'.jpg"
fetch_image "Sedge, Blue Ridge" "Carex lucorum" "Sedge, Blue Ridge.jpg"
fetch_image "Sedge, Bristle-stalk" "Carex leptalea" "Sedge, Bristle-stalk.jpg"
fetch_image "Sedge, Brownish" "Carex brunnescens" "Sedge, Brownish.jpg"
fetch_image "Sedge, Chaffy" "Carex paleacea" "Sedge, Chaffy.jpg"
fetch_image "Sedge, Common Fox" "Carex vulpinoidea" "Sedge, Common Fox.jpg"
fetch_image "Sedge, Crawford's" "Carex crawfordii" "Sedge, Crawford's.jpg"
fetch_image "Sedge, Cyperus-like" "Carex pseudocyperus" "Sedge, Cyperus-like.jpg"
fetch_image "Sedge, Fibrous-rooted" "Carex communis" "Sedge, Fibrous-rooted.jpg"
fetch_image "Sedge, Fringed" "Carex crinita" "Sedge, Fringed.jpg"
fetch_image "Sedge, Graceful" "Carex gracillima" "Sedge, Graceful.jpg"
fetch_image "Sedge, Greater Bladder" "Carex intumescens" "Sedge, Greater Bladder.jpg"
fetch_image "Sedge, Hoary" "Carex canescens" "Sedge, Hoary.jpg"
fetch_image "Sedge, Houghton's" "Carex houghtoniana" "Sedge, Houghton's.jpg"
fetch_image "Sedge, Little Green" "Carex viridula" "Sedge, Little Green.jpg"
fetch_image "Sedge, Mackenzie's" "Carex mackenzii" "Sedge, Mackenzie's.jpg"
fetch_image "Sedge, Marsh Straw" "Carex hormathodes" "Sedge, Marsh Straw.jpg"
fetch_image "Sedge, Merritt Fernald's" "Carex merritt-fernaldii" "Sedge, Merritt Fernald's.jpg"
fetch_image "Sedge, Necklace" "Carex projecta" "Sedge, Necklace.jpg"
fetch_image "Sedge, New England" "Carex novae-angliae" "Sedge, New England.jpg"
fetch_image "Sedge, Nodding" "Carex gynandra" "Sedge, Nodding.jpg"
fetch_image "Sedge, Northeastern" "Carex cryptolepis" "Sedge, Northeastern.jpg"
fetch_image "Sedge, Open Field" "Carex conoidea" "Sedge, Open Field.jpg"
fetch_image "Sedge, Pale" "Carex pallescens" "Sedge, Pale.jpg"
fetch_image "Sedge, Parasol" "Carex umbellata" "Sedge, Parasol.jpg"
fetch_image "Sedge, Pointed Broom" "Carex scoparia" "Sedge, Pointed Broom.jpg"
fetch_image "Sedge, Prickly Bog" "Carex atlantica" "Sedge, Prickly Bog.jpg"
fetch_image "Sedge, Sallow" "Carex lurida" "Sedge, Sallow.jpg"
fetch_image "Sedge, Sea-beach" "Carex silicia" "Sedge, Sea-beach.jpg"
fetch_image "Sedge, Shaved" "Carex tonsa" "Sedge, Shaved.jpg"
fetch_image "Sedge, Smooth Black" "Carex nigra" "Sedge, Smooth Black.jpg"
fetch_image "Sedge, Soft-leaved" "Carex disperma" "Sedge, Soft-leaved.jpg"
fetch_image "Sedge, Star" "Carex echinata" "Sedge, Star.jpg"
fetch_image "Sedge, Swarthy" "Carex adusta" "Sedge, Swarthy.jpg"
fetch_image "Sedge, Three-seeded" "Carex trisperma" "Sedge, Three-seeded.jpg"
fetch_image "Sedge, Three-way" "Dulichium arundinaceum" "Sedge, Three-way.jpg"
fetch_image "Sedge, Tussock" "Carex stricta" "Sedge, Tussock.jpg"
fetch_image "Sedge, White-edged" "Carex debilis" "Sedge, White-edged.jpg"
fetch_image "Sedge, White-tinged" "Carex albicans" "Sedge, White-tinged.jpg"
fetch_image "Sedge, Wooly-fruited" "Carex lasiocarpa" "Sedge, Wooly-fruited.jpg"
fetch_image "Selfheal, Common" "Prunella vulgaris" "Selfheal, Common.jpg"
fetch_image "Shadbush, Downy" "Amelanchier arborea" "Shadbush, Downy.jpg"
fetch_image "Shadbush, Dwarf" "Amelanchier spicata" "Shadbush, Dwarf.jpg"
fetch_image "Shadbush, Mountain" "Amelanchier bartramiana" "Shadbush, Mountain.jpg"
fetch_image "Shadbush, Smooth" "Amelanchier laevis" "Shadbush, Smooth.jpg"
fetch_image "Sheep Fescue, Fine-leaved" "Festuca filiformis" "Sheep Fescue, Fine-leaved.jpg"
fetch_image "Sheep-laurel" "Kalmia angustifolia" "Sheep-laurel.jpg"
fetch_image "Shepherd's Purse" "Capsella bursa-pastoris" "Shepherd's Purse.jpg"
fetch_image "Shinleaf, American" "Pyrola americana" "Shinleaf, American.jpg"
fetch_image "Shinleaf, Elliptic-leaved" "Pyrola elliptica" "Shinleaf, Elliptic-leaved.jpg"
fetch_image "Shinleaf, One-flowered" "Moneses uniflora" "Shinleaf, One-flowered.jpg"
fetch_image "Silverweed, Pacific" "Argentina egedii" "Silverweed, Pacific.jpg"
fetch_image "Skullcap, Hooded" "Scutellaria galericulata" "Skullcap, Hooded.jpg"
fetch_image "Skunk-cabbage" "Symplocarpus foetidus" "Skunk-cabbage.jpg"
fetch_image "Smartweed, Dotted" "Persicaria punctata" "Smartweed, Dotted.jpg"
fetch_image "Smartweed, False Water-pepper" "Persicaria hydropiperoides" "Smartweed, False Water-pepper.jpg"
fetch_image "Smartweed, Lady's-thumb" "Persicaria maculosa" "Smartweed, Lady's-thumb.jpg"
fetch_image "Solomon's Seal, Feathery False" "Maianthemum racemosum" "Solomon's Seal, Feathery False.jpg"
fetch_image "Solomon's Seal, Star-like False" "Maianthemum stellatum" "Solomon's Seal, Star-like False.jpg"
fetch_image "Solomon's Seal, Three-leaved False" "Maianthemum trifolium" "Solomon's Seal, Three-leaved False.jpg"
fetch_image "Sow-thistle, Field" "Sonchus arvensis" "Sow-thistle, Field.jpg"
fetch_image "Sow-thistle, Spiny-leaved" "Sonchus asper" "Sow-thistle, Spiny-leaved.jpg"
fetch_image "Speedwell, Common" "Veronica officinalis" "Speedwell, Common.jpg"
fetch_image "Speedwell, Corn" "Veronica arvensis" "Speedwell, Corn.jpg"
fetch_image "Speedwell, Purslane" "Veronica peregrina" "Speedwell, Purslane.jpg"
fetch_image "Speedwell, Thyme-leaved" "Veronica serpyllifolia" "Speedwell, Thyme-leaved.jpg"
fetch_image "Spikemoss, Ledge" "Selaginella rupestris" "Spikemoss, Ledge.jpg"
fetch_image "Spikesedge Uniglumis" "Eleocharis uniglumis" "Spikesedge Uniglumis.jpg"
fetch_image "Spikesedge, Blunt" "Eleocharis obtusa" "Spikesedge, Blunt.jpg"
fetch_image "Spikesedge, Common" "Eleocharis palustris" "Spikesedge, Common.jpg"
fetch_image "Spikesedge, Elliptic" "Eleocharis elliptica" "Spikesedge, Elliptic.jpg"
fetch_image "Spikesedge, Needle" "Eleocharis acicularis" "Spikesedge, Needle.jpg"
fetch_image "Spikesedge, Slender" "Eleocharis tenuis" "Spikesedge, Slender.jpg"
fetch_image "Spiraea, False" "Sorbaria sorbifolia" "Spiraea, False.jpg"
fetch_image "Spleenwort, Maidenhair" "Asplenium trichomanes" "Spleenwort, Maidenhair.jpg"
fetch_image "Spleenwort, Silvery False" "Deparia acrostichoides" "Spleenwort, Silvery False.jpg"
fetch_image "Spruce, Black" "Picea mariana" "Spruce, Black.jpg"
fetch_image "Spruce, Red" "Picea rubens" "Spruce, Red.jpg"
fetch_image "Spruce, White" "Picea glauca" "Spruce, White.jpg"
fetch_image "Spurge, Leafy" "Euphorbia esula" "Spurge, Leafy.jpg"
fetch_image "St. John's-wort, Fraser's Marsh" "Triadenum fraseri" "St. John's-wort, Fraser's Marsh.jpg"
fetch_image "St. John's-wort, Lesser Canada" "Hypericum canadense" "St. John's-wort, Lesser Canada.jpg"
fetch_image "St. John's-wort, Northern" "Hypericum boreale" "St. John's-wort, Northern.jpg"
fetch_image "St. John's-wort, Orange-grass" "Hypericum gentianoides" "St. John's-wort, Orange-grass.jpg"
fetch_image "St. John's-wort, Spotted" "Hypericum punctatum" "St. John's-wort, Spotted.jpg"
fetch_image "Starflower" "Lysimachia borealis" "Starflower.jpg"
fetch_image "Stichwort, Bog" "Stellaria alsine" "Stichwort, Bog.jpg"
fetch_image "Stichwort, Common" "Stellaria media" "Stichwort, Common.jpg"
fetch_image "Stichwort, Grass-leaved" "Stellaria graminea" "Stichwort, Grass-leaved.jpg"
fetch_image "Stichwort, Long-leaved" "Stellaria longifolia" "Stichwort, Long-leaved.jpg"
fetch_image "Stonecrop, Moss" "Sedum acre" "Stonecrop, Moss.jpg"
fetch_image "Stonecrop, Spanish" "Sedum hispanicum" "Stonecrop, Spanish.jpg"
fetch_image "Strawberry, Common" "Fragaria virginiana" "Strawberry, Common.jpg"
fetch_image "Sumac, Staghorn" "Rhus hirta" "Sumac, Staghorn.jpg"
fetch_image "Sundew, Round-leaved" "Drosera rotundifolia" "Sundew, Round-leaved.jpg"
fetch_image "Sundew, Spatulate-leaved" "Drosera intermedia" "Sundew, Spatulate-leaved.jpg"
fetch_image "Sweet Grass, Large" "Anthoxanthum odoratum" "Sweet Grass, Large.jpg"
fetch_image "Sweet-cicely, Bland" "Osmorhiza claytonii" "Sweet-cicely, Bland.jpg"
fetch_image "Sweet-clover, Yellow" "Melilotus officinalis" "Sweet-clover, Yellow.jpg"
fetch_image "Sweet-fern" "Comptonia peregrina" "Sweet-fern.jpg"
fetch_image "Sweetgale" "Myrica gale" "Sweetgale.jpg"
fetch_image "Tansy, Common" "Tanacetum vulgare" "Tansy, Common.jpg"
fetch_image "Tansy, Feverfew" "Tanacetum parthenium" "Tansy, Feverfew.jpg"
fetch_image "Tearthumb, Arrow-leaved" "Persicaria sagittata" "Tearthumb, Arrow-leaved.jpg"
fetch_image "Thistle, Common" "Cirsium vulgare" "Thistle, Common.jpg"
fetch_image "Thistle, Creeping" "Cirsium arvense" "Thistle, Creeping.jpg"
fetch_image "Thistle, Swamp" "Cirsium muticum" "Thistle, Swamp.jpg"
fetch_image "Thoroughwort" "Eupatorium perfoliatum" "Thoroughwort.jpg"
fetch_image "Timothy, Common" "Phleum pratense" "Timothy, Common.jpg"
fetch_image "Toadflax, Butter-and-eggs" "Linaria vulgaris" "Toadflax, Butter-and-eggs.jpg"
fetch_image "Toadflax, Oldfield" "Nuttallanthus canadensis" "Toadflax, Oldfield.jpg"
fetch_image "Touch-me-not, Himalaya" "Impatiens glandulifera" "Touch-me-not, Himalaya.jpg"
fetch_image "Touch-me-not, Spotted" "Impatiens capensis" "Touch-me-not, Spotted.jpg"
fetch_image "Trailing-arbutus" "Epigaea repens" "Trailing-arbutus.jpg"
fetch_image "Tuber-bulrush, Saltmarsh" "Bolboschoenus maritimus" "Tuber-bulrush, Saltmarsh.jpg"
fetch_image "Twinflower, American" "Linnaea borealis" "Twinflower, American.jpg"
fetch_image "Valerian, Common" "Valeriana officinalis" "Valerian, Common.jpg"
fetch_image "Vetch, Crown" "Coronilla varia" "Vetch, Crown.jpg"
fetch_image "Vetch, Hairy" "Vicia villosa" "Vetch, Hairy.jpg"
fetch_image "Vetchling, Beach" "Lathyrus japonicus" "Vetchling, Beach.jpg"
fetch_image "Violet, Blue Marsh" "Viola cucullata" "Violet, Blue Marsh.jpg"
fetch_image "Violet, Hook-spurred" "Viola adunca" "Violet, Hook-spurred.jpg"
fetch_image "Violet, Lance-leaved" "Viola lanceolata" "Violet, Lance-leaved.jpg"
fetch_image "Violet, Smooth White" "Viola pallens" "Violet, Smooth White.jpg"
fetch_image "Violet, Sweet White" "Viola blanda" "Violet, Sweet White.jpg"
fetch_image "Violet, Wooly Blue" "Viola sororia" "Violet, Wooly Blue.jpg"
fetch_image "Virginia Creeper" "Parthenocissus quinquefolia" "Virginia Creeper.jpg"
fetch_image "Wakerobin, Painted" "Trillium undulatum" "Wakerobin, Painted.jpg"
fetch_image "Water Shield" "Brasenia schreberi" "Water Shield.jpg"
fetch_image "Water-hemlock, Spotted" "Cicuta maculata" "Water-hemlock, Spotted.jpg"
fetch_image "Water-horehound, American" "Lycopus americanus" "Water-horehound, American.jpg"
fetch_image "Water-horehound, Northern" "Lycopus uniflorus" "Water-horehound, Northern.jpg"
fetch_image "Water-horehound, Virginia" "Lycopus virginicus" "Water-horehound, Virginia.jpg"
fetch_image "Water-lily, White" "Nymphaea odorata" "Water-lily, White.jpg"
fetch_image "Water-starwort, Vernal" "Callitriche palustris" "Water-starwort, Vernal.jpg"
fetch_image "Whitlow-mustard, Spring" "Draba verna" "Whitlow-mustard, Spring.jpg"
fetch_image "Wild Lovage, Scotch" "Ligusticum scoticum" "Wild Lovage, Scotch.jpg"
fetch_image "Wild-rye, Common Eastern" "Elymus virginicus" "Wild-rye, Common Eastern.jpg"
fetch_image "Wild-rye, Creeping" "Elymus repens" "Wild-rye, Creeping.jpg"
fetch_image "Wild-rye, Slender" "Elymus trachycaulus" "Wild-rye, Slender.jpg"
fetch_image "Willow-herb, Bog" "Epilobium leptophyllum" "Willow-herb, Bog.jpg"
fetch_image "Willow-herb, Eastern" "Epilobium coloratum" "Willow-herb, Eastern.jpg"
fetch_image "Willow-herb, Fringed" "Epilobium ciliatum" "Willow-herb, Fringed.jpg"
fetch_image "Willow, Balsam" "Salix pyrifolia" "Willow, Balsam.jpg"
fetch_image "Willow, Meadow" "Salix petiolaris" "Willow, Meadow.jpg"
fetch_image "Willow, Prairie" "Salix humilis" "Willow, Prairie.jpg"
fetch_image "Willow, Pussy" "Salix discolor" "Willow, Pussy.jpg"
fetch_image "Willow, Shining" "Salix lucida" "Willow, Shining.jpg"
fetch_image "Winterberry, Common" "Ilex verticillata" "Winterberry, Common.jpg"
fetch_image "Wintergreen, Creeping Spicy" "Gaultheria hispidula" "Wintergreen, Creeping Spicy.jpg"
fetch_image "Wintergreen, Eastern Spicy" "Gaultheria procumbens" "Wintergreen, Eastern Spicy.jpg"
fetch_image "Withe-rod, Wild-raisin" "Viburnum nudum" "Withe-rod, Wild-raisin.jpg"
fetch_image "Wood Sorrel, Common Yellow" "Oxalis stricta" "Wood Sorrel, Common Yellow.jpg"
fetch_image "Wood Sorrel, Flowering Yellow" "Oxalis florida" "Wood Sorrel, Flowering Yellow.jpg"
fetch_image "Wood Sorrel, Northern" "Oxalis montana" "Wood Sorrel, Northern.jpg"
fetch_image "Woodrush, Common" "Luzula multiflora" "Woodrush, Common.jpg"
fetch_image "Woolsedge, Black-girdled" "Scirpus atrocinctus" "Woolsedge, Black-girdled.jpg"
fetch_image "Woolsedge, Common" "Scirpus cyperinus" "Woolsedge, Common.jpg"
fetch_image "Wormwood, Beach" "Artemisia stelleriana" "Wormwood, Beach.jpg"
fetch_image "Wormwood, Common" "Artemisia vulgaris" "Wormwood, Common.jpg"
fetch_image "Yarrow, Common" "Achillea millefolium" "Yarrow, Common.jpg"
fetch_image "Yellow-cress" "Rorippa palustris" "Yellow-cress.jpg"
fetch_image "Yellow-rattle, Little" "Rhinanthus minor" "Yellow-rattle, Little.jpg"
fetch_image "Yellow-rocket, Garden" "Barbarea vulgaris" "Yellow-rocket, Garden.jpg"
fetch_image "Yew, American" "Taxus canadensis" "Yew, American.jpg"
fetch_image "Bearberry, Common" "Arctostaphylos uva-ursi" "Bearberry, Common.jpg"
fetch_image "Bedstraw, Smooth" "Galium mollugo" "Bedstraw, Smooth.jpg"
fetch_image "Centaury, Dyer's" "Gentiana tinctoria" "Centaury, Dyer's.jpg"

echo ""
echo "================================================="
# Count results
total=0; success=0
for dir in "Beech, American" "Beggar-ticks, Devil's" "Bellflower, Creeping" "Bellflower, Marsh" "Bellflower, Scotch" "Bentgrass, Autumn" "Bentgrass, Creeping" "Bentgrass, Redtop" "Bentgrass, Rhode Island" "Bentgrass, Rough" "Bindweed, Black" "Bindweed, Crested" "Bindweed, Fringed" "Bindweed, Hedge False" "Birch, Blue" "Birch, Gray" "Birch, Heart-leaved Paper" "Birch, Paper" "Birch, Yellow" "Bitter-cress, Small-flowered" "Bittersweet, Asian" "Blackberry, Arching" "Blackberry, Bristly" "Blackberry, Common" "Blackberry, Northern" "Blackberry, Showy" "Blackberry, Smooth" "Blackberry, Vermont" "Bladderwort, Greater" "Bladderwort, Mixed" "Aster, Blake's" "Blue Grass, Flat-stemmed" "Blue Grass, Fowl" "Blue Grass, Wood" "Blue-eyed-grass, Narrow-leaved" "Blue-eyed-grass, Strict" "Hair Grass, Tufted" "Hair Sedge, Tufted" "Hawkweed, Canada" "Hawkweed, Mouse-ear" "Hawkweed, Orange" "Hawkweed, Panicled" "Hawkweed, Rough" "Hawkweed, Yellow" "Hawthorn, Miss Jones'" "Hazelnut, Beaked" "Helleborine, Broad-leaved" "Hemlock, Eastern" "Hemp-nettle, Brittle-stemmed" "Hemp-nettle, Split-lipped" "Highbush-cranberry" "Holly, Mountain" "Honeysuckle, American" "Honeysuckle, Bush" "Honeysuckle, Morrow's" "Horsetail, Field" "Horsetail, Wood" "Huckleberry, Black" "Indian-pipe, One-flowered" "Iris, Blue" "Jack-in-the-pulpit" "Juniper, Common" "Juniper, Creeping" "Knapweed, Black" "Knapweed, Brown" "Knotweed, Dooryard" "Knotweed, Fowler's" "Knotweed, Japanese" "Knotweed, Prairie" "Labrador-tea" "Ladies'-tresses, Hooded" "Ladies'-tresses, Nodding" "Lady's Slipper, Pink" "Larch, American" "Larkspur, Tall" "Leatherleaf" "Lobelia, Bladder-pod" "Locust, Black" "Loosestrife, Garden Yellow" "Loosestrife, Purple" "Loosestrife, Swamp Yellow" "Loosestrife, Whorled Yellow" "Lupine, Blue" "Lyme Grass, American" "Mallow, Musk" "Manna Grass, American" "Manna Grass, Fowl" "Manna Grass, Rattlesnake" "Maple, Mountain" "Maple, Norway" "Maple, Red" "Maple, Striped" "Maple, Sugar" "Marigold, Pot" "Marjoram, Wild" "Marsh-pennywort" "Mayflower, Canada" "Meadow-foxtail, Field" "Meadow-foxtail, Marsh" "Meadow-rue, Tall" "Meadowsweet, Rosy" "Meadowsweet, White" "Medick, Black" "Milkweed, Common" "Mint, Field" "Mint, Ginger Spear" "Mistletoe, Dwarf" "Mountain-ash, American" "Mountain-ash, European" "Mountain-ash, Showy" "Mullein, Common" "Mustard, Chinese" "Nettle, Small-spiked False" "Nettle, Stinging" "Nightshade, Climbing" "Nightshade, European Black" "Oak, Northern Red" "Oatgrass, Flattened" "Oatgrass, Poverty" "Orache, Bracted" "Orache, Hastate-leaved" "Orache, Maritime" "Orchid, Loesel's Wide-lipped" "Orpine, Purple" "Oxtongue, Hawkweed" "Panicgrass, Hairy Rosette-" "Panicgrass, Northern Rosette-" "Pearlwort, Birds-eye" "Pearlwort, Knotted" "Pickerelweed" "Pimpernel, Scarlet" "Pine-sap, Yellow" "Pine, Pitch" "Pine, Red" "Pine, White" "Pink, Deptford" "Pink, Maiden" "Pinweed, Round-fruited" "Pitcherplant, Purple" "Plantain, Common" "Plantain, English" "Plantain, Seaside" "Plum, Canada" "Pogonia, Rose" "Poison-ivy" "Poison-ivy, Western" "Polypody, Appalachian" "Polypody, Rock" "Pond-lily, Bullhead" "Pondweed, Alga-like" "Pondweed, Oakes'" "Pondweed, Ribbon-leaved" "Poplar, Balsam" "Princes-pine, Spotted" "Pumpkin" "Pussytoes, Small" "Queen Anne's Lace" "Quickweed" "Radish, Wild" "Ragweed, Common" "Ragwort, Common" "Ragwort, Tansy" "Ragwort, Woodland" "Raspberry, Dwarf" "Raspberry, Red" "Rattlesnake-root, Three-leaved" "Rattlesnake-plantain, Dwarf" "Reed Grass, Canada" "Rhodora" "Rose, Beach" "Rose, Cinnamon" "Rose, Rambler" "Rose, Shining" "Rose, Swamp" "Rose, Sweet-briar" "Rose, Virginia" "Rush, Baltic" "Rush, Brown-fruited" "Rush, Canada" "Rush, Common Soft" "Rush, Dudley's" "Rush, Path" "Rush, Pylae's Soft" "Rush, Saltmarsh" "Rush, Short-tailed" "Rush, Thread" "Rush, Toad" "Russian-olive" "Saltgrass" "Sand-spurry, Canada" "Sand-spurry, Red" "Sand-spurry, Saltmarsh" "Sandwort, Seaside" "Sandwort, Thyme-leaved" "Sarsaparilla, Bristly" "Sarsaparilla, Wild" "Sea-blite, American" "Sea-blite, Herbaceous" "Sea-lavender, Carolina" "Sea-milkwort" "Sea-rocket, American" "Sedge, Awl-fruited" "Sedge, Billings'" "Sedge, Blue Ridge" "Sedge, Bristle-stalk" "Sedge, Brownish" "Sedge, Chaffy" "Sedge, Common Fox" "Sedge, Crawford's" "Sedge, Cyperus-like" "Sedge, Fibrous-rooted" "Sedge, Fringed" "Sedge, Graceful" "Sedge, Greater Bladder" "Sedge, Hoary" "Sedge, Houghton's" "Sedge, Little Green" "Sedge, Mackenzie's" "Sedge, Marsh Straw" "Sedge, Merritt Fernald's" "Sedge, Necklace" "Sedge, New England" "Sedge, Nodding" "Sedge, Northeastern" "Sedge, Open Field" "Sedge, Pale" "Sedge, Parasol" "Sedge, Pointed Broom" "Sedge, Prickly Bog" "Sedge, Sallow" "Sedge, Sea-beach" "Sedge, Shaved" "Sedge, Smooth Black" "Sedge, Soft-leaved" "Sedge, Star" "Sedge, Swarthy" "Sedge, Three-seeded" "Sedge, Three-way" "Sedge, Tussock" "Sedge, White-edged" "Sedge, White-tinged" "Sedge, Wooly-fruited" "Selfheal, Common" "Shadbush, Downy" "Shadbush, Dwarf" "Shadbush, Mountain" "Shadbush, Smooth" "Sheep Fescue, Fine-leaved" "Sheep-laurel" "Shepherd's Purse" "Shinleaf, American" "Shinleaf, Elliptic-leaved" "Shinleaf, One-flowered" "Silverweed, Pacific" "Skullcap, Hooded" "Skunk-cabbage" "Smartweed, Dotted" "Smartweed, False Water-pepper" "Smartweed, Lady's-thumb" "Solomon's Seal, Feathery False" "Solomon's Seal, Star-like False" "Solomon's Seal, Three-leaved False" "Sow-thistle, Field" "Sow-thistle, Spiny-leaved" "Speedwell, Common" "Speedwell, Corn" "Speedwell, Purslane" "Speedwell, Thyme-leaved" "Spikemoss, Ledge" "Spikesedge Uniglumis" "Spikesedge, Blunt" "Spikesedge, Common" "Spikesedge, Elliptic" "Spikesedge, Needle" "Spikesedge, Slender" "Spiraea, False" "Spleenwort, Maidenhair" "Spleenwort, Silvery False" "Spruce, Black" "Spruce, Red" "Spruce, White" "Spurge, Leafy" "St. John's-wort, Fraser's Marsh" "St. John's-wort, Lesser Canada" "St. John's-wort, Northern" "St. John's-wort, Orange-grass" "St. John's-wort, Spotted" "Starflower" "Stichwort, Bog" "Stichwort, Common" "Stichwort, Grass-leaved" "Stichwort, Long-leaved" "Stonecrop, Moss" "Stonecrop, Spanish" "Strawberry, Common" "Sumac, Staghorn" "Sundew, Round-leaved" "Sundew, Spatulate-leaved" "Sweet Grass, Large" "Sweet-cicely, Bland" "Sweet-clover, Yellow" "Sweet-fern" "Sweetgale" "Tansy, Common" "Tansy, Feverfew" "Tearthumb, Arrow-leaved" "Thistle, Common" "Thistle, Creeping" "Thistle, Swamp" "Thoroughwort" "Timothy, Common" "Toadflax, Butter-and-eggs" "Toadflax, Oldfield" "Touch-me-not, Himalaya" "Touch-me-not, Spotted" "Trailing-arbutus" "Tuber-bulrush, Saltmarsh" "Twinflower, American" "Valerian, Common" "Vetch, Crown" "Vetch, Hairy" "Vetchling, Beach" "Violet, Blue Marsh" "Violet, Hook-spurred" "Violet, Lance-leaved" "Violet, Smooth White" "Violet, Sweet White" "Violet, Wooly Blue" "Virginia Creeper" "Wakerobin, Painted" "Water Shield" "Water-hemlock, Spotted" "Water-horehound, American" "Water-horehound, Northern" "Water-horehound, Virginia" "Water-lily, White" "Water-starwort, Vernal" "Whitlow-mustard, Spring" "Wild Lovage, Scotch" "Wild-rye, Common Eastern" "Wild-rye, Creeping" "Wild-rye, Slender" "Willow-herb, Bog" "Willow-herb, Eastern" "Willow-herb, Fringed" "Willow, Balsam" "Willow, Meadow" "Willow, Prairie" "Willow, Pussy" "Willow, Shining" "Winterberry, Common" "Wintergreen, Creeping Spicy" "Wintergreen, Eastern Spicy" "Withe-rod, Wild-raisin" "Wood Sorrel, Common Yellow" "Wood Sorrel, Flowering Yellow" "Wood Sorrel, Northern" "Woodrush, Common" "Woolsedge, Black-girdled" "Woolsedge, Common" "Wormwood, Beach" "Wormwood, Common" "Yarrow, Common" "Yellow-cress" "Yellow-rattle, Little" "Yellow-rocket, Garden" "Yew, American" "Bearberry, Common" "Bedstraw, Smooth" "Centaury, Dyer's"; do
    total=$((total + 1))
    if [ -n "$(find "$WILDLIFE_DIR/$dir" -name '*.jpg' -o -name '*.JPG' -o -name '*.png' 2>/dev/null)" ]; then
        success=$((success + 1))
    fi
done
echo "Downloaded: $success / $total"
